import { Link } from "react-router-dom";
import { ArrowLeft, Scale } from "lucide-react";

const Disclaimer = () => (
  <div className="min-h-screen bg-background px-4 py-6">
    <div className="max-w-lg mx-auto">
      <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground text-sm mb-6">
        <ArrowLeft className="w-4 h-4" /> Back
      </Link>

      <div className="rounded-2xl bg-gradient-to-br from-blue-500 to-blue-700 p-6 text-white mb-5 shadow-lg shadow-blue-500/30">
        <Scale className="w-7 h-7 mb-2 opacity-90" />
        <h1 className="font-display font-black text-3xl">Disclaimer</h1>
        <p className="text-blue-100 text-sm mt-1">A quick, honest heads-up before you study.</p>
      </div>

      <div className="glass rounded-xl p-5 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <p>Hello, lovely learner 👋 — we built NeuroLearn to make studying feel a little less lonely and a lot more fun. Before you scroll through reels and mock tests, here are a few important things to keep in mind.</p>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">1. For learning, not for diagnosis</h2>
          <p>Every lesson, note, MCQ, and mock test on NeuroLearn is for educational and informational purposes only. We're a study companion — not a substitute for school, teachers, certified tutors, or official syllabus documents.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">2. AI is smart, not perfect</h2>
          <p>A lot of our content is generated by AI models. Most of the time it's spot-on, but every now and then it might slip up — a wrong year, off formula, or an outdated fact. Please cross-check important things against NCERT books, your coaching material, or official exam websites.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">3. We can't promise ranks</h2>
          <p>Your JEE rank, NEET score, UPSC selection, or board percentage depends on so many things — your effort, consistency, mental health, exam-day luck. NeuroLearn helps you study smarter, but the magic happens because of <em>you</em>.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">4. Not affiliated with exam boards</h2>
          <p>We're a private platform. Names like JEE, NEET, UPSC, SSC, CBSE belong to their respective organisations. We're not officially partnered with or endorsed by any of them.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">5. External links & ads</h2>
          <p>Some pages may include ads (to keep NeuroLearn free) or links to other websites. We don't control what happens on those sites — please use your own judgement before sharing data or making purchases there.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">6. Take care of yourself</h2>
          <p>Studying matters, but so does sleep, food, friends, and a walk in the sun. If you ever feel overwhelmed, please talk to someone you trust. NeuroLearn will still be here when you come back. 💙</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">7. Talk to us</h2>
          <p>Found a mistake in a lesson? Have an idea? Want to say hi? Email <a href="mailto:mantalmath6@gmail.com" className="text-blue-600 font-semibold">mantalmath6@gmail.com</a> — we genuinely read every message.</p>
        </section>

        <p className="text-xs pt-2 border-t border-border/40">
          <strong className="text-foreground">Last updated:</strong> June 2026
        </p>
      </div>
    </div>
  </div>
);

export default Disclaimer;
