import { Link } from "react-router-dom";
import { ArrowLeft, Scale, Sparkles, BookOpen, AlertTriangle, Mail, Heart } from "lucide-react";

const Disclaimer = () => (
  <div className="min-h-screen bg-background px-4 py-6">
    <div className="max-w-2xl mx-auto">
      <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground text-sm mb-6">
        <ArrowLeft className="w-4 h-4" /> Back
      </Link>
      <h1 className="font-display font-black text-3xl md:text-4xl mb-2">
        <span className="gradient-text">Disclaimer</span>
      </h1>
      <p className="text-sm text-muted-foreground mb-8">
        A quick, friendly note about how to use NeuroLearn wisely. Nothing scary — just honest expectations.
      </p>

      <div className="space-y-5 text-[15px] leading-relaxed text-foreground/90">
        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <BookOpen className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">For Learning, Not Last-Minute Miracles</h2>
          </div>
          <p>
            NeuroLearn is built to help you study smarter, every day. It's an amazing supplement to your
            school, college, or coaching — but it's not a magic shortcut. Consistent practice still wins. Use
            us as a daily study buddy, not as the only thing between you and your exam. 💙
          </p>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">About Our AI Content</h2>
          </div>
          <p>
            A lot of our lessons, quizzes, and explanations are generated by AI. We work hard to make sure
            everything is accurate and aligned with the NCERT and exam syllabus, but AI is not perfect — once
            in a while, a tiny mistake might slip through. If you ever spot something off, please tell us and
            we'll fix it fast. Always double-check important facts with your official textbooks.
          </p>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <Scale className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">No Guarantees of Ranks or Results</h2>
          </div>
          <p>
            We love it when our students crack JEE, NEET, UPSC, SSC and Boards — and many do! But we can't
            promise a specific rank, score, or selection. Exam success depends on your effort, consistency,
            and circumstances. NeuroLearn is here to give you the best tools and content possible; the
            hard work is still yours to put in (we know you've got this).
          </p>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">Not Professional Advice</h2>
          </div>
          <p>
            Our content is purely educational. It is not legal, medical, financial, or career advice. For
            big life decisions — like which college to join, which career to pick, or anything related to your
            health — please consult qualified professionals. We're here to teach concepts, not to make life
            decisions for you.
          </p>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <Heart className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">External Links & Ads</h2>
          </div>
          <p>
            Sometimes we may link to outside websites or show ads. We don't control what those sites do, and
            we're not responsible for their content. Use your own judgment, and never share personal
            information on sites you don't trust.
          </p>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-2">
            <Mail className="w-5 h-5 text-primary" />
            <h2 className="font-display font-bold text-lg">Talk to Us</h2>
          </div>
          <p>
            Found a mistake, have a concern, or want to suggest a better explanation? Please write to us at{" "}
            <a href="mailto:mantalmath6@gmail.com" className="text-primary font-medium underline">
              mantalmath6@gmail.com
            </a>
            . We genuinely care, and we'll act on it. Now go ace those lessons. You've got this! 🚀
          </p>
        </div>

        <p className="text-center text-xs text-muted-foreground pt-2">
          Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long" })}
        </p>
      </div>
    </div>
  </div>
);

export default Disclaimer;
