import { useNavigate, Link } from "react-router-dom";
import { Sparkles, BookOpen, Brain, Zap, Trophy, ArrowRight, Shield, FileText, Mail, Info, Scale } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  { icon: Sparkles, title: "60-Second Lessons", desc: "Bite-sized, reel-style learning that sticks" },
  { icon: Brain, title: "AI-Powered", desc: "Personalized content generated by AI" },
  { icon: BookOpen, title: "Exam Mode", desc: "JEE, NEET, UPSC, SSC & Board prep" },
  { icon: Trophy, title: "Gamified", desc: "Streaks, XP, badges & leaderboards" },
];

const Landing = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <section className="relative overflow-hidden px-4 pt-20 pb-16">
        <div className="absolute inset-0 opacity-30">
          <div className="absolute top-20 left-10 w-72 h-72 rounded-full bg-primary/20 blur-3xl" />
          <div className="absolute bottom-20 right-10 w-72 h-72 rounded-full bg-secondary/20 blur-3xl" />
        </div>
        <div className="relative max-w-lg mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 glass rounded-full px-4 py-1.5 text-xs font-medium mb-6">
              <Zap className="w-3 h-3 text-primary" />
              <span>AI-Powered Micro-Learning</span>
            </div>
            <h1 className="font-display font-black text-4xl md:text-5xl leading-tight mb-4">
              Learn Anything in{" "}
              <span className="gradient-text">60 Seconds</span>
            </h1>
            <p className="text-muted-foreground text-base mb-8 max-w-sm mx-auto">
              Swipe through addictive, reel-style lessons. Ace JEE, NEET, UPSC & more with AI-powered micro-learning.
            </p>
            <button
              onClick={() => navigate("/auth")}
              className="gradient-primary text-primary-foreground font-display font-semibold px-8 py-3 rounded-xl text-base hover:opacity-90 transition-opacity inline-flex items-center gap-2 animate-pulse-glow"
            >
              Start Learning Free
              <ArrowRight className="w-4 h-4" />
            </button>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="px-4 pb-16">
        <div className="max-w-lg mx-auto grid grid-cols-2 gap-3">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.1 * i }}
              className="glass rounded-xl p-4"
            >
              <f.icon className="w-6 h-6 text-primary mb-2" />
              <h3 className="font-display font-semibold text-sm mb-1">{f.title}</h3>
              <p className="text-muted-foreground text-xs">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Exam Highlight */}
      <section className="px-4 pb-16">
        <div className="max-w-lg mx-auto glass rounded-2xl p-6 text-center">
          <BookOpen className="w-8 h-8 text-primary mx-auto mb-3" />
          <h2 className="font-display font-bold text-xl mb-2">Exam Mode</h2>
          <p className="text-muted-foreground text-sm mb-4">
            Dedicated prep for JEE Main, JEE Advanced, NEET, UPSC, SSC & Board Exams
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            {["JEE Main", "NEET", "UPSC", "SSC", "Boards"].map((exam) => (
              <span key={exam} className="glass rounded-full px-3 py-1 text-xs font-medium">
                {exam}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="px-4 pb-16">
        <div className="max-w-lg mx-auto">
          <h2 className="font-display font-bold text-xl text-center mb-6">Simple Pricing</h2>
          <div className="grid grid-cols-2 gap-3">
            <div className="glass rounded-xl p-4">
              <h3 className="font-display font-semibold text-sm mb-1">Free</h3>
              <p className="font-display font-bold text-2xl mb-2">₹0</p>
              <ul className="text-xs text-muted-foreground space-y-1">
                <li>• 5 lessons/day</li>
                <li>• Basic exams</li>
                <li>• Streaks & XP</li>
              </ul>
            </div>
            <div className="rounded-xl p-4 gradient-primary text-primary-foreground">
              <h3 className="font-display font-semibold text-sm mb-1">Pro</h3>
              <p className="font-display font-bold text-2xl mb-2">₹199<span className="text-sm font-normal">/mo</span></p>
              <ul className="text-xs opacity-90 space-y-1">
                <li>• Unlimited lessons</li>
                <li>• All exam modes</li>
                <li>• AI generation</li>
                <li>• No ads</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-4 pb-12">
        <div className="max-w-lg mx-auto text-center">
          <button
            onClick={() => navigate("/auth")}
            className="gradient-primary text-primary-foreground font-display font-semibold px-8 py-3 rounded-xl text-base hover:opacity-90 transition-opacity"
          >
            Start Learning Free
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 bg-muted/30 px-4 py-8">
        <div className="max-w-lg mx-auto">
          <div className="flex items-center justify-center gap-2 mb-6">
            <div className="w-7 h-7 rounded-lg gradient-primary flex items-center justify-center">
              <Zap className="w-4 h-4 text-primary-foreground" />
            </div>
            <span className="font-display font-bold text-lg">NeuroLearn</span>
          </div>
          <div className="grid grid-cols-2 gap-3 mb-6">
            <Link to="/about" className="flex items-center gap-2 text-muted-foreground hover:text-foreground text-xs transition-colors">
              <Info className="w-3.5 h-3.5" /> About Us
            </Link>
            <Link to="/contact" className="flex items-center gap-2 text-muted-foreground hover:text-foreground text-xs transition-colors">
              <Mail className="w-3.5 h-3.5" /> Contact Us
            </Link>
            <Link to="/privacy" className="flex items-center gap-2 text-muted-foreground hover:text-foreground text-xs transition-colors">
              <Shield className="w-3.5 h-3.5" /> Privacy Policy
            </Link>
            <Link to="/terms" className="flex items-center gap-2 text-muted-foreground hover:text-foreground text-xs transition-colors">
              <FileText className="w-3.5 h-3.5" /> Terms & Conditions
            </Link>
            <Link to="/disclaimer" className="flex items-center gap-2 text-muted-foreground hover:text-foreground text-xs transition-colors">
              <Scale className="w-3.5 h-3.5" /> Disclaimer
            </Link>
          </div>
          <p className="text-center text-[10px] text-muted-foreground">
            © {new Date().getFullYear()} NeuroLearn. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
