import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, BookText, Sparkles } from "lucide-react";
import { getChapters } from "@/data/studyMaterial";

const StudyChapters = () => {
  const { examType, subject, classLevel } = useParams<{ examType: string; subject: string; classLevel: string }>();
  const navigate = useNavigate();
  const decodedSubject = decodeURIComponent(subject || "");
  const decodedClass = decodeURIComponent(classLevel || "");
  const chapters = getChapters(examType || "boards", decodedSubject, decodedClass);

  const grouped = chapters.reduce<Record<string, typeof chapters>>((acc, ch) => {
    const k = ch.book || "Chapters";
    (acc[k] ||= []).push(ch);
    return acc;
  }, {});

  return (
    <div className="px-4 py-4 pb-24">
      <button onClick={() => navigate(`/study/${examType}/${encodeURIComponent(decodedSubject)}`)} className="flex items-center gap-1.5 text-muted-foreground text-sm mb-4 hover:text-foreground transition-colors">
        <ArrowLeft className="w-4 h-4" />
        <span>{decodedSubject}</span>
      </button>

      <div className="flex items-center gap-2 mb-1">
        <BookText className="w-5 h-5 text-primary" />
        <h2 className="font-display font-bold text-xl">{decodedClass} — {decodedSubject}</h2>
      </div>
      <p className="text-muted-foreground text-sm mb-1">{chapters.length} chapters available</p>
      <p className="text-[11px] text-primary mb-5 flex items-center gap-1">
        <Sparkles className="w-3 h-3" /> Notes, questions & mock tests generated by AI
      </p>

      {Object.entries(grouped).map(([book, list]) => (
        <div key={book} className="mb-5">
          {book !== "Chapters" && (
            <h3 className="font-display font-semibold text-xs uppercase tracking-wide text-muted-foreground mb-2">{book}</h3>
          )}
          <div className="space-y-2.5">
            {list.map((ch, i) => (
              <button
                key={ch.id}
                onClick={() => navigate(`/study/${examType}/${encodeURIComponent(decodedSubject)}/${encodeURIComponent(decodedClass)}/${ch.id}`)}
                className="w-full glass rounded-xl p-4 flex items-center gap-3 hover:bg-muted/30 transition-colors active:scale-[0.98]"
              >
                <div className="w-9 h-9 rounded-lg gradient-primary flex items-center justify-center text-primary-foreground font-display font-bold text-sm shrink-0">
                  {i + 1}
                </div>
                <div className="text-left min-w-0 flex-1">
                  <p className="font-display font-semibold text-sm truncate">{ch.name}</p>
                  <p className="text-muted-foreground text-[10px] flex items-center gap-1">
                    <Sparkles className="w-2.5 h-2.5 text-primary" /> AI Notes • Questions • Mock
                  </p>
                </div>
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
};

export default StudyChapters;
