import { Link } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";

const Terms = () => (
  <div className="min-h-screen bg-background px-4 py-6">
    <div className="max-w-lg mx-auto">
      <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground text-sm mb-6">
        <ArrowLeft className="w-4 h-4" /> Back
      </Link>

      <div className="rounded-2xl bg-gradient-to-br from-blue-500 to-blue-700 p-6 text-white mb-5 shadow-lg shadow-blue-500/30">
        <FileText className="w-7 h-7 mb-2 opacity-90" />
        <h1 className="font-display font-black text-3xl">Terms & Conditions</h1>
        <p className="text-blue-100 text-sm mt-1">The friendly rulebook for using NeuroLearn.</p>
      </div>

      <div className="glass rounded-xl p-5 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <p>Hi 👋 — by using NeuroLearn you're agreeing to a few small ground rules. We've kept them short and human so you actually read them. Take a sip of chai and scroll through.</p>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">1. Welcome aboard</h2>
          <p>Creating an account or using NeuroLearn in any way means you accept these terms. If anything here doesn't sit right with you, no worries — please don't use the app. We respect your choice.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">2. Your account, your responsibility</h2>
          <p>Use a real email, pick a strong password, and please don't share your login with anyone. If something fishy happens with your account, tell us right away and we'll help.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">3. How you can use the content</h2>
          <p>All lessons, notes, AI-generated material and mock tests are made for your personal learning. Feel free to screenshot, take notes in your diary, or quiz your friends. But please don't scrape the content or resell it — that's a hard no.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">4. Be cool to each other</h2>
          <p>We're building a community of learners. No abuse, no spam, no cheating, and no posting copyrighted material you don't own. We may remove accounts that break these basics.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">5. Pro subscriptions</h2>
          <p>Pro plans renew monthly. You can cancel anytime from your profile — you'll keep Pro features until the end of your billing cycle. No surprise charges.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">6. AI content notice</h2>
          <p>Notes, MCQs, and mock tests are generated by AI. We work hard to keep them accurate, but please cross-verify with NCERT or trusted sources before your exam. Think of NeuroLearn as your study buddy, not the official answer key.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">7. What we can't promise</h2>
          <p>We can't guarantee specific exam ranks, marks, or career outcomes — your effort and luck play a huge role. NeuroLearn is provided "as is", and to the extent allowed by law we're not liable for indirect losses.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">8. Changes to the app</h2>
          <p>We're constantly improving. Features may change, get better, or occasionally be retired. When something big happens, we'll let you know inside the app.</p>
        </section>

        <section>
          <h2 className="font-display font-semibold text-blue-600 mb-1">9. Talking to us</h2>
          <p>Questions about these terms? Want to flag a problem? We're real humans: <a href="mailto:mantalmath6@gmail.com" className="text-blue-600 font-semibold">mantalmath6@gmail.com</a>.</p>
        </section>

        <p className="text-xs pt-2 border-t border-border/40">
          <strong className="text-foreground">Last updated:</strong> June 2026 · Thanks for being part of NeuroLearn. 💙
        </p>
      </div>
    </div>
  </div>
);

export default Terms;
